---
spring:
  application:
    name: employee-service

server:
  port: ${PORT:8082}

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadata-map:
      version: 1.0.0
      cluster: DEV          # Required by Turbine (see turbine project's application.yml)
      zone: AWS-EU-FRA      # Specify the zone this service is running in. Used to match clients in the same zone first.
    healthcheck: 
      enabled: true
      
# configurations of the actuator /info endpoint
info: 
  app:
    name: "Employee Service"
    description: "An employee service instance."

      
---
spring.profiles: cloud

eureka:
  client: 
    serviceUrl:
      defaultZone: ${eureka-server-url}/eureka  # URL of the form https://<unique prefix>-eureka-server.cfapps.eu10.hana.ondemand.com/eureka
                                                # Resolved from environment set in manifest.yml
  instance:
    ## This information will be part of the InstanceInfo returned by DiscoveryClient / EurekaClient.
    ## Unfortunately, these have to be specified explicitly, since Eureka creates these URLs wrongly
    ## when running on CF. 
    ## See: https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html
    homePageUrl:          https://${vcap.application.uris[0]:localhost}/   
    statusPageUrl:        https://${vcap.application.uris[0]:localhost}/actuator/info 
    healthCheckUrl:       https://${vcap.application.uris[0]:localhost}/actuator/health
    secureHealthCheckUrl: https://${vcap.application.uris[0]:localhost}/actuator/health
    ## set the host name explicitly when in Cloud Foundry.
    hostname:             ${vcap.application.uris[0]:localhost}
    nonSecurePortEnabled: false
    securePortEnabled:    true
    securePort:           443
    #nonSecurePort:       80
    #preferIpAddress:     true
    metadataMap:
      # Adding information about the application GUID to 
      # each instance metadata. This could be used by Ribbon
      applicationGUID: ${vcap.application.application_id}
      # No need to replicate this information in metadata. 
      # It is available from InstanceInfo.
      # instanceId: "${vcap.application.instance_id:-}"


